language: node_js
node_js:
  - node
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - npm test
  - npm run production
deploy:
  provider: surge
  project: ./dist/
  domain: convulator.surge.sh
  skip_cleanup: true
